<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="UseCases\Incomes\Reports\Pdf\Fonts\BebasNeue-Regular.ttf" />
    <None Remove="UseCases\Incomes\Reports\Pdf\Fonts\Roboto-Medium.ttf" />
    <None Remove="UseCases\Incomes\Reports\Pdf\Fonts\Roboto-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="UseCases\Incomes\Reports\Pdf\Fonts\BebasNeue-Regular.ttf" />
    <EmbeddedResource Include="UseCases\Incomes\Reports\Pdf\Fonts\Roboto-Medium.ttf" />
    <EmbeddedResource Include="UseCases\Incomes\Reports\Pdf\Fonts\Roboto-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BarberBoss.Communication\BarberBoss.Communication.csproj" />
    <ProjectReference Include="..\BarberBoss.Domain\BarberBoss.Domain.csproj" />
    <ProjectReference Include="..\BarberBoss.Exception\BarberBoss.Exception.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Logo\ProfilePhoto.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
